# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from example import helloworld_pb2 as example_dot_helloworld__pb2


class GreeterStub(object):
    """option java_package = "com.example.grpc";
    option java_outer_classname = "HelloWorldServiceProto";
    option java_multiple_files = true;
    import public "google/protobuf/timestamp.proto";

    The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/example.Greeter/SayHello',
                request_serializer=example_dot_helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=example_dot_helloworld__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """option java_package = "com.example.grpc";
    option java_outer_classname = "HelloWorldServiceProto";
    option java_multiple_files = true;
    import public "google/protobuf/timestamp.proto";

    The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=example_dot_helloworld__pb2.HelloRequest.FromString,
                    response_serializer=example_dot_helloworld__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """option java_package = "com.example.grpc";
    option java_outer_classname = "HelloWorldServiceProto";
    option java_multiple_files = true;
    import public "google/protobuf/timestamp.proto";

    The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Greeter/SayHello',
            example_dot_helloworld__pb2.HelloRequest.SerializeToString,
            example_dot_helloworld__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
